### ISSUE TITLE
Comments can’t be uncommented in VS Code

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/markdown-tm-language#3]
Create an MDX file with the following content:

```mdx
This is markdown

export function foo() {
  return
}
```

Select a range that starts at the first line of the exported function. Press <kbd>Ctrl</kbd> + <kbd>/</kbd> a couple of times.

#### Expected behaviour

Comments are toggled

#### Actual behaviour

This has awkward behaviour that eventually results in `// ` prefix being added several times.

Comment behaviour has always been awkward in MDX, because there are different contexts of nested languages, but it has gotten worse with the new language definition.

**Comment by wooorm** [comment]
> but it has gotten worse with the new language definition.

I disagree. They were completely broken. It has improved.

---

This is likely unrelated to syntax highlighting but related to VS Code.
There are other `tm*` files I can generate here, which are used by Sublime, Atom, and TextMate, which relate to comments, but I don’t think VS Code uses them.
Take for example https://github.com/microsoft/vscode/tree/main/extensions/typescript-basics, that doesn’t have other `tm*` files.

There are two problems you describe:

1. mixed languages, every VS Code language has this problem. Try some HTML:
   ```
   <script>a
     b
   c</script>
   ```
2. commenting some markdown (`a` -> `{/* a */}`) can’t be uncommented (-> `// {/* a */}`)
   This must be fixable, because for the HTML `<script>asd</script>`, VS Code switches to `<!-- <script>asd</script> -->`, so it knows it’s about HTML, even though there’s JS in there.

VS Code has three commands, to add (CMD+K+C), to remove (CMD+K+I), and to toggle (CMD+/).
But uncommenting doesn’t work correctly in MDX. Try with `{/* a */}` **and** `// {/* asd */}`, CMD+K+U. Does weird things

**Comment by wooorm** [comment]
Found it. Comments and more work through https://github.com/mdx-js/mdx-analyzer/blob/ef42008fba129dc4d5b3aee3de63f9757bc2044d/packages/vscode-mdx/package.json#L131. Which attach to something in this grammar. Which was classified more broadly than it should’ve been!

**Comment by remcohaszing** [comment]
I’m inclined to believe you here. This is not my expertise.

I didn’t even know of the commands to add or remove comments. I just always toggle.

The TypeScript language service has [some functions](https://github.com/mdx-js/mdx-analyzer/blob/v1.3.0/packages/language-service/lib/index.js#L863-L866) related to commenting, but they’re not implemented. I don’t see anything related to comments in the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/). TypeScript in VSCode doesn’t use a language server, so maybe they use that for smarter contexts.

**Comment by wooorm** [comment]
> language service

That too was one hunch when I learned there are different commands, that there might be something missing in our MDX language server!
